version: '3'

services:
  course_hunter:
    image: course_hunter
    build: .
    user: "node"
    environment:
      - NODE_ENV=development
      - TZ=Asia/Shanghai
    volumes: 
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js